### ISSUE TITLE
How To Use Examples

### ISSUE THREAD

**Issue by stephencweiss** [enquirer/enquirer#218]
Hi there! 

I'm pretty new to command line and am excited that I found `enquirer`! I spent some time looking around open issues and through the repo before writing this, but still, it might not be the right place for this question.

Basically, I wanted to get a sense of how `enquirer` works and play around with it - so when I saw the examples, that felt like a natural place to go.

Based on the .gif in the README, it looked like I should be able to run `node examples/survey/prompt.js`. When I did, however, I received the following error:
```shell
$ node examples/survey/prompt.js
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module 'enquirer'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/stephen/_coding/personal/enquirer/examples/survey/prompt.js:3:20)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
```

I received this error even after installing the local packages _and_ installing `enquirer` globally.

I did ultimately get it to work by starting a new project and installing `enquirer` locally for that project, then copying the example over.

What I'm unclear on is whether that's the expected flow or if there was something I did wrong within the fork of `enquirer` I have that I could have done differently to get the examples to work there?

Thanks!

P.S. What's the motivation for the `.npmrc` to not have `node_modules`?

**Comment by jonschlinkert** [comment]
There is a `package.json` in the examples folder, you'll need to `cd` into the examples folder and run `npm install` first. Thanks for creating the issue, well make sure to document that better. 

> P.S. What's the motivation for the `.npmrc` to not have `node_modules`?

The `.npmrc` file is to prevent the `package-lock.json` file from being used, it doesn't do anything to `node_modules`.

**Comment by stephencweiss** [comment]
Ah - must have missed the `package.json` in the examples. Thanks for the heads up! 

And that’s what I meant. Why is it helpful to _not_ have a `package-lock.json`? (This is the first time I’ve ever seen it, so it just caught me by surprise and I’m trying to learn.)

Thanks!
