### ISSUE TITLE
AutoComplete Exception - Long List with the string matching [a-zA-Z][0-9]

### ISSUE THREAD

**Issue by jestrjk** [enquirer/enquirer#237]
Using autocomplete with an array of about 200 choices, with a limit of 20 and using a filter string that matches one of the array choices at the end of the string with  [a-zA-Z][0-9] pattern for example:

choices = [ 'some long string Q1', ...choices ]

when filtering by 'Q1', the result is an unhandled exception:

UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'enabled' of undefined
    at number (/home/<redacted>/aws-log-finder/alf/node_modules/enquirer/lib/types/array.js:276:19)
    at handle (/home/<redacted>/aws-log-finder/alf/node_modules/enquirer/lib/types/array.js:307:18)
    at /home/<redacted>/aws-log-finder/alf/node_modules/enquirer/lib/types/array.js:313:16
    at new Promise (<anonymous>)-
    at AutoComplete.number (/home/<redacted>/aws-log-finder/alf/node_modules/enquirer/lib/types/array.js:301:12)
    at AutoComplete.keypress (/home/<redacted>/aws-log-finder/alf/node_modules/enquirer/lib/prompt.js:44:17)
    at ReadStream.on (/home/<redacted>/aws-log-finder/alf/node_modules/enquirer/lib/keypress.js:205:26)

**Comment by jestrjk** [comment]
https://github.com/enquirer/enquirer/blob/2796b25facb1f6914ffaecf9413e98209cb98a4d/lib/types/array.js#L276

Linked: #237 

This line could be changed to:
`if ( !choice || ( !choice.enabled && this.selected.length >= this.maxSelected )) {`

**Comment by adityavyas611** [comment]
Hi, @jestrjk Could you please share your code, so I can have a better look at the issue?
