### ISSUE TITLE
Exceptions in `validate` causes "Unhandled promise rejection" errors

### ISSUE THREAD

**Issue by sqren** [enquirer/enquirer#277]
enquirer currently doesn't handle exceptions thrown in `validate` very gracefully.

**Expected result**
I'd expect that the exception thrown in `validate` below would cause the prompt to be cancelled, and the exception caught in the `catch` ("Oops, error: ...").

```js
const { prompt } = require("enquirer");

const question = {
  type: "input",
  name: "username",
  message: "What is your username?",
  async validate(value, state) {
    throw new Error("boo!");
  },
};

prompt(question)
  .then((answer) => console.log("Answer:", answer))
  .catch(e => {
    console.log('Oops, error:', e)
  });
```

**What actually happens**
The prompt is not cancelled and the error is not captured in `catch` but instead ends up as an unhandled promise rejection:

```
? What is your username? › asa (node:9358) UnhandledPromiseRejectionWarning: Error: boo!
    at Input.validate (/Users/sqren/srv/enquirer-demo/index.js:8:11)
    at Input.submit (/Users/sqren/srv/enquirer-demo/node_modules/enquirer/lib/prompt.js:123:49)
    at Input.submit (/Users/sqren/srv/enquirer-demo/node_modules/enquirer/lib/prompts/input.js:51:18)
    at Input.keypress (/Users/sqren/srv/enquirer-demo/node_modules/enquirer/lib/prompt.js:44:23)
    at Input.keypress (/Users/sqren/srv/enquirer-demo/node_modules/enquirer/lib/types/string.js:24:18)
    at ReadStream.on (/Users/sqren/srv/enquirer-demo/node_modules/enquirer/lib/keypress.js:205:26)
    at ReadStream.emit (events.js:203:15)
    at emitKeys (internal/readline.js:424:14)
    at emitKeys.next (<anonymous>)
    at ReadStream.onData (readline.js:1073:36)
(node:9358) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:9358) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Why not just handle the error inside `validate`?**
That was my first though. Depending on the exception it might be of a severity that the application needs to be terminated entirely - or at least handled on an application level - which means there needs to be a mechanism for bubbling up exceptions that occur within `validate`.

**Comment by sqren** [comment]
I took a shot at fixing this and created a PR https://github.com/enquirer/enquirer/pull/278. This is by no means a perfect solution but a first rough draft to demonstrate what I'm hoping for.
