### ISSUE TITLE
Skip causes multiselect to error

### ISSUE THREAD

**Issue by LoaderB0T** [enquirer/enquirer#298]
Hi all!

I just discovered that passing true to the skip option on a multiselect prompt causes an error.

You can reproduce the issue with this code snippet:

```javascript
const prompt = require('enquirer');

const skipThisPrompt = true;

(async () => {
  const ans = await prompt.prompt({
    type: 'multiselect',
    name: 'myName',
    message: 'yaya',
    choices: ['first choice', 'second choice'],
    skip: skipThisPrompt
  });
  console.log(ans.myName);
})();
```

I tried to debug and analyze this issue myself but quickly realized that debugging JS is not my strength...
However, the error gets initially thrown in the lib/types/array.js file in line 509.
this.state._choices is undefined. Maybe this is a small error, as I saw during debugging that this.state.choices (without the underscore) exists and has the expected choices.

Maybe somebody with more javascript skills can analyze this further.

Thanks!

**Comment by doowb** [comment]
@LoaderB0T thanks for the issue. I can confirm this is a bug.

**Comment by elmijo** [comment]
I'm running same issue, but I could find a way to make it work setting the value of `_choices` property. i don't like it but it could help if you cannot wait to the official fix. 

```js
     skip() {
        // eslint-disable-next-line no-underscore-dangle
        this.state._choices = this.state.choices; // <----  _choices is a copy of choices or at latest I saw that in the State object
        return this.state.answers.scope === 'global';
      }
```

I was following the code,  and looks like event that property is set here https://github.com/enquirer/enquirer/blob/master/lib/types/array.js#L31, but when skip logic is called, `_choices` doesn't exists in the State.

This is the error:

```bash
node_modules/enquirer/lib/types/array.js:509
    let result = choices.filter(fn);
                         ^

TypeError: Cannot read properties of undefined (reading 'filter')
    at MultiSelect.filter (node_modules/enquirer/lib/types/array.js:509:26)
    at MultiSelect.get enabled [as enabled] (node_modules/enquirer/lib/types/array.js:620:17)
    at MultiSelect.get selected [as selected] (node_modules/enquirer/lib/types/array.js:636:33)
    at MultiSelect.submit (node_modules/enquirer/lib/types/array.js:546:22)
    at node_modules/enquirer/lib/prompt.js:234:21
```

**Comment by massi-ang** [comment]
Is this going to be fixed?
