### ISSUE TITLE
stdin and stdout option issues

### ISSUE THREAD

**Issue by kerruba-milkman** [enquirer/enquirer#338]
Hello, 
I'm having issues when passing `stdin` and `stdout` options to the Enquirer object.
Here my snippet of code
```
    let Enquirer = require('enquirer')
    let enquirer = new Enquirer({stdin: process.stdin, stdout: process.stdout})
    return enquirer.prompt(questions);
```

Here the error I get
```
message: this.stdout.write is not a function
stack: TypeError: this.stdout.write is not a function
    at AutoComplete.cursorHide (<project-path>/node_modules/enquirer/lib/prompt.js:59:17)
    at new ArrayPrompt (<project-path>/node_modules/enquirer/lib/types/array.js:12:10)
    at new SelectPrompt (<project-path>/node_modules/enquirer/lib/prompts/select.js:8:5)
    at new AutoComplete (<project-path>/node_modules/enquirer/lib/prompts/autocomplete.js:17:5)
    at Enquirer.ask (<project-path>/node_modules/enquirer/index.js:107:18)
    at Enquirer.prompt (<project-path>/node_modules/enquirer/index.js:82:20)
```
This happens even when I want to use a different stream, like a stream generating by opening a new tty session

Here the list of questions I'm passing to enquirer
```
    let questions = [
        {
            type: 'autocomplete',
            multiple: true,
            name: 'instance',
            message: 'Which instances do you want to check?',
            choices: instances,
            skip: function() {
                return options.hasOwnProperty('instance')
            }
        },
        {
            type: 'confirm',
            name: 'all',
            message: 'Do you want to list all results?',
            skip: function(label) {
                if (options.hasOwnProperty(label)) {
                    this.enquirer.answers[label] = true
                    return true
                }
                if (options.hasOwnProperty('service')) {
                    this.enquirer.answers[label] = false
                    return true
                }
                return false
            },
            initial: 'y'
        },
        {
            type: 'list',
            name: 'service',
            message: 'Service names (comma-separated)',
            skip: function(label) {
                return this.enquirer.answers['all'] || options.hasOwnProperty(label)
            }
        }
```

**Comment by busticated** [comment]
does this fix it? https://github.com/enquirer/enquirer/pull/309

**Comment by Kerruba** [comment]
@busticated actually I saw your issue before and I thought it was already been released, but I just realised it wasn't. 
Yeah it seems that #309 fixes the issue, so I suppose we just need to wait for your fix to be released

**Comment by kerruba-milkman** [comment]
@jonschlinkert Do you know if there's any plan to release #309? that's probably going to fix this issue

**Comment by KaKi87** [comment]
Hello,

Since that PR still isn't released, I added directly added `git+https://github.com/enquirer/enquirer.git` as dependency.

The `this.stdout.write is not a function` is gone, but I'm now experiencing the [`Invalid stream passed` error](https://github.com/enquirer/enquirer/blob/8d626c206733420637660ac7c2098d7de45e8590/lib/keypress.js#L199).

If I understand this correctly, the library only accepts `tty.ReadableStream` & `tty.WritableStream` instances but not `stream.Readable` & `stream.Writable` insances.

So, I tried creating `tty.ReadableStream` & `tty.WritableStream` instances and pipe my existing `stream.Readable` & `stream.Writable` into those, but these constructors require an `fd` parameter for which I can't find documentation anywhere.

By the way, what I'm actually trying to do is to use `enquirer` through [`ssh2`](https://github.com/mscdex/ssh2).

Thanks
