### ISSUE TITLE
v2.4.0 contains changes that are not compatible with Node 14

### ISSUE THREAD

**Issue by chenjiahan** [enquirer/enquirer#432]
**enquirer 2.4.0 cannot run in Node.js <= 16 because it uses incompatible syntax.** Many existing projects are broken due to this change.

```bash
(node:80580) UnhandledPromiseRejectionWarning: /pnpm/enquirer@2.4.0/node_modules/enquirer/lib/types/string.js:33
      this.state.multilineBuffer ||= '';
                                 ^^^

SyntaxError: Unexpected token '||='
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
```

@jonschlinkert Can you revert these changes and release them in 3.0.0?

Related issues:

- https://github.com/enquirer/enquirer/issues/431

**Comment by chenjiahan** [comment]
@jonschlinkert I would love to, a PR has been submitted: #433

Looking forward to the hotfix version soon. 😄
