### ISSUE TITLE
Issue related to Windows mintty

### ISSUE THREAD

**Issue by javoski** [enquirer/enquirer#62]
OS: Window 10
Terminal: mintty 2.9.4 along with Git

```
(node:28480) UnhandledPromiseRejectionWarning: Error: Invalid stream passed
    at Function.keypress.listen (D:\Workspace\test\enquirer-test\node_modules\enquirer\lib\keypress.js:191:11)
    at SelectPrompt.start (D:\Workspace\test\enquirer-test\node_modules\enquirer\lib\prompt.js:158:28)
    at SelectPrompt.initialize (D:\Workspace\test\enquirer-test\node_modules\enquirer\lib\prompt.js:167:16)
    at SelectPrompt.initialize (D:\Workspace\test\enquirer-test\node_modules\enquirer\lib\types\array.js:21:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
(node:28480) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:28480) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

BTW: Examples in this repo are running normally, this issue only happened when used through `require('enquirer')`.

**Comment by jonschlinkert** [comment]
Looks like `process.stdin` isn't a stream. I might need to get some help from someone with a Windows box to debug this.

**Comment by jonschlinkert** [comment]
@javoski if you have a moment, please pull down Enquirer 2.3.0 and let me know if that solves the issue for you. Thanks!

**Comment by javoski** [comment]
@jonschlinkert It works. Well done!

**Comment by jonschlinkert** [comment]
Great! thanks for the feedback. The fix was provided by @whxaxes in https://github.com/enquirer/enquirer/pull/101.
